# Generated by Django 5.1.1 on 2024-10-10 07:54

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contract_title_alter_contract_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractproject',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
